import { Sensor, Notification, HouseInfo, DashboardStats, SensorHistory } from "./types";
import { subHours, subMinutes, format } from "date-fns";

export const mockSensors: Sensor[] = [
  {
    id: "s1",
    name: "Термометр гостиная",
    type: "temperature",
    room: "Гостиная",
    espIp: "192.168.1.101",
    espName: "ESP-Living",
    value: 22.4,
    unit: "°C",
    status: "online",
    lastUpdated: new Date().toISOString(),
    batteryLevel: 85,
    minThreshold: 16,
    maxThreshold: 28,
  },
  {
    id: "s2",
    name: "Влажность гостиная",
    type: "humidity",
    room: "Гостиная",
    espIp: "192.168.1.101",
    espName: "ESP-Living",
    value: 55,
    unit: "%",
    status: "online",
    lastUpdated: new Date().toISOString(),
    batteryLevel: 85,
    minThreshold: 30,
    maxThreshold: 70,
  },
  {
    id: "s3",
    name: "Термометр спальня",
    type: "temperature",
    room: "Спальня",
    espIp: "192.168.1.102",
    espName: "ESP-Bedroom",
    value: 19.8,
    unit: "°C",
    status: "online",
    lastUpdated: new Date().toISOString(),
    batteryLevel: 62,
    minThreshold: 16,
    maxThreshold: 24,
  },
  {
    id: "s4",
    name: "Датчик движения прихожая",
    type: "motion",
    room: "Прихожая",
    espIp: "192.168.1.103",
    espName: "ESP-Hall",
    value: false,
    unit: "",
    status: "online",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "s5",
    name: "Датчик дыма кухня",
    type: "smoke",
    room: "Кухня",
    espIp: "192.168.1.104",
    espName: "ESP-Kitchen",
    value: false,
    unit: "",
    status: "online",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "s6",
    name: "CO₂ гостиная",
    type: "co2",
    room: "Гостиная",
    espIp: "192.168.1.101",
    espName: "ESP-Living",
    value: 620,
    unit: "ppm",
    status: "warning",
    lastUpdated: new Date().toISOString(),
    minThreshold: 400,
    maxThreshold: 1000,
  },
  {
    id: "s7",
    name: "Освещённость кабинет",
    type: "light",
    room: "Кабинет",
    espIp: "192.168.1.105",
    espName: "ESP-Office",
    value: 340,
    unit: "lx",
    status: "online",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "s8",
    name: "Датчик протечки ванная",
    type: "water_leak",
    room: "Ванная",
    espIp: "192.168.1.106",
    espName: "ESP-Bath",
    value: false,
    unit: "",
    status: "online",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "s9",
    name: "Давление воздух",
    type: "pressure",
    room: "Гостиная",
    espIp: "192.168.1.101",
    espName: "ESP-Living",
    value: 101.3,
    unit: "кПа",
    status: "online",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "s10",
    name: "Датчик двери входная",
    type: "door",
    room: "Прихожая",
    espIp: "192.168.1.103",
    espName: "ESP-Hall",
    value: false,
    unit: "",
    status: "offline",
    lastUpdated: subHours(new Date(), 2).toISOString(),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    title: "Высокий уровень CO₂",
    message: "Уровень CO₂ в гостиной достиг 620 ppm. Рекомендуется проветрить помещение.",
    severity: "warning",
    sensorId: "s6",
    sensorName: "CO₂ гостиная",
    room: "Гостиная",
    timestamp: subMinutes(new Date(), 15).toISOString(),
    read: false,
  },
  {
    id: "n2",
    title: "Датчик двери офлайн",
    message: "Датчик двери «Входная» не отвечает более 2 часов. Проверьте питание устройства.",
    severity: "critical",
    sensorId: "s10",
    sensorName: "Датчик двери входная",
    room: "Прихожая",
    timestamp: subHours(new Date(), 2).toISOString(),
    read: false,
  },
  {
    id: "n3",
    title: "Движение обнаружено",
    message: "Датчик движения в прихожей зафиксировал активность.",
    severity: "info",
    sensorId: "s4",
    sensorName: "Датчик движения прихожая",
    room: "Прихожая",
    timestamp: subHours(new Date(), 3).toISOString(),
    read: true,
  },
  {
    id: "n4",
    title: "Температура в норме",
    message: "Температура в спальне вернулась в норму — 19.8°C.",
    severity: "info",
    sensorId: "s3",
    sensorName: "Термометр спальня",
    room: "Спальня",
    timestamp: subHours(new Date(), 5).toISOString(),
    read: true,
  },
  {
    id: "n5",
    title: "Низкий заряд батареи",
    message: "Датчик температуры в спальне: заряд батареи 62%. Рекомендуется замена в течение недели.",
    severity: "warning",
    sensorId: "s3",
    sensorName: "Термометр спальня",
    room: "Спальня",
    timestamp: subHours(new Date(), 8).toISOString(),
    read: true,
  },
];

export const mockHouseInfo: HouseInfo = {
  name: "Мой умный дом",
  address: "г. Москва, ул. Примерная, д. 1, кв. 42",
  area: 85,
  floors: 1,
  owner: "Иванов Иван",
  timezone: "Europe/Moscow",
  rooms: [
    { id: "r1", name: "Гостиная", icon: "sofa", area: 22, floor: 1, sensors: ["s1", "s2", "s6", "s9"] },
    { id: "r2", name: "Спальня", icon: "bed", area: 18, floor: 1, sensors: ["s3"] },
    { id: "r3", name: "Кухня", icon: "utensils", area: 14, floor: 1, sensors: ["s5"] },
    { id: "r4", name: "Кабинет", icon: "monitor", area: 12, floor: 1, sensors: ["s7"] },
    { id: "r5", name: "Прихожая", icon: "door-open", area: 8, floor: 1, sensors: ["s4", "s10"] },
    { id: "r6", name: "Ванная", icon: "droplets", area: 7, floor: 1, sensors: ["s8"] },
  ],
  espDevices: [
    {
      id: "esp1",
      name: "ESP-Living",
      ip: "192.168.1.101",
      status: "online",
      firmware: "v2.3.1",
      lastSeen: new Date().toISOString(),
      sensors: ["s1", "s2", "s6", "s9"],
      rssi: -52,
      uptime: 86400 * 12,
    },
    {
      id: "esp2",
      name: "ESP-Bedroom",
      ip: "192.168.1.102",
      status: "online",
      firmware: "v2.3.1",
      lastSeen: new Date().toISOString(),
      sensors: ["s3"],
      rssi: -64,
      uptime: 86400 * 7,
    },
    {
      id: "esp3",
      name: "ESP-Hall",
      ip: "192.168.1.103",
      status: "online",
      firmware: "v2.2.0",
      lastSeen: new Date().toISOString(),
      sensors: ["s4", "s10"],
      rssi: -71,
      uptime: 86400 * 3,
    },
    {
      id: "esp4",
      name: "ESP-Kitchen",
      ip: "192.168.1.104",
      status: "online",
      firmware: "v2.3.1",
      lastSeen: new Date().toISOString(),
      sensors: ["s5"],
      rssi: -58,
      uptime: 86400 * 15,
    },
    {
      id: "esp5",
      name: "ESP-Office",
      ip: "192.168.1.105",
      status: "online",
      firmware: "v2.1.5",
      lastSeen: new Date().toISOString(),
      sensors: ["s7"],
      rssi: -67,
      uptime: 86400 * 4,
    },
    {
      id: "esp6",
      name: "ESP-Bath",
      ip: "192.168.1.106",
      status: "online",
      firmware: "v2.3.1",
      lastSeen: new Date().toISOString(),
      sensors: ["s8"],
      rssi: -73,
      uptime: 86400 * 9,
    },
  ],
};

export const mockDashboardStats: DashboardStats = {
  totalSensors: mockSensors.length,
  onlineSensors: mockSensors.filter((s) => s.status === "online").length,
  offlineSensors: mockSensors.filter((s) => s.status === "offline").length,
  warningSensors: mockSensors.filter((s) => s.status === "warning").length,
  unreadNotifications: mockNotifications.filter((n) => !n.read).length,
  rooms: mockHouseInfo.rooms.length,
  espDevices: mockHouseInfo.espDevices.length,
  espOnline: mockHouseInfo.espDevices.filter((e) => e.status === "online").length,
};

function generateHistory(
  baseValue: number,
  hoursBack: number,
  variance: number
): { timestamp: string; value: number }[] {
  const readings = [];
  const now = new Date();
  const pointsPerHour = 4;
  const total = hoursBack * pointsPerHour;

  for (let i = total; i >= 0; i--) {
    const time = subMinutes(now, i * (60 / pointsPerHour));
    const noise = (Math.random() - 0.5) * variance * 2;
    const drift = Math.sin((i / total) * Math.PI * 2) * variance * 0.5;
    readings.push({
      timestamp: format(time, "HH:mm"),
      value: Math.round((baseValue + noise + drift) * 10) / 10,
    });
  }
  return readings;
}

export const mockSensorHistories: Record<string, { timestamp: string; value: number }[]> = {
  s1: generateHistory(22, 24, 2),
  s2: generateHistory(55, 24, 5),
  s3: generateHistory(20, 24, 1.5),
  s6: generateHistory(600, 24, 80),
  s7: generateHistory(300, 24, 150),
  s9: generateHistory(101.3, 24, 0.5),
};
